name: Trading Service CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-24.04-arm

    env:
      BUILD_CONFIGURATION: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Trading.sln

    - name: Build
      run: dotnet build Trading.sln --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Run tests
      timeout-minutes: 15
      run: dotnet test Trading.sln --configuration ${{ env.BUILD_CONFIGURATION }} --logger trx --results-directory ${{ runner.temp }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: upload test-results
        path: ${{ runner.temp }}/*.trx

    - name: 'Test Report'
      uses: dorny/test-reporter@v1
      with:
        name: Test Results
        path: ${{ runner.temp }}/*.trx
        reporter: dotnet-trx
        fail-on-error: false

    - name: Build and Push Docker Image
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker buildx build \
          --platform linux/arm64 \
          -f src/Trading.API/Dockerfile \
          -t ghcr.io/${{ github.actor }}/trading:latest \
          --push .